{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cd2d0030",
   "metadata": {},
   "source": [
    "# Fantasy Premier League 2021/2022 Season Analysis:\n",
    "\n",
    "\n",
    "## Project Description:\n",
    "**About the game**: Fantasy Premier League (FPL) is a game played by 8m+ people globally and points are scored based on real-life outcomes in the English Premier League. Each FPL manager is given a starting budget of £100 million and must pick a total of 15 players: two goalkeepers, five defenders, five midfielders and three forwards. You are limited to a maximum of three players from each Premier League team. Players in your team score points based on real-life performances with the main contributors to points totals being goals, assists (attacking returns) and cleansheets (defensive returns).\n",
    "\n",
    "The FPL team provides multiple API endpoints to get various stats on teams, players, FPL managers and the game itself. We are only concerened with player data so we will be consuming the https://fantasy.premierleague.com/api/bootstrap-static/ endpoint.\n",
    "\n",
    "The question that we are trying to answer is: **Can we use data analytics to help us find undervalued players?**\n",
    "\n",
    "Why undervalued? These are the players that I believe will elevate you from an average FPL manager to one of the top FPL managers. We will analyze teams, positions and players to give us insight into where and how to find these players. \n",
    "\n",
    "\n",
    "## Table Of Contents:\n",
    "\n",
    "The project includes two Jupyter Notebooks and a folder containing raw aand clean data sorted by season:\n",
    "\n",
    "1. Data Loading & Preprocessing\n",
    "\n",
    "2. Exploratory Data Analysis\n",
    "\n",
    "A summary of the tasks completed and findings are listed below. The notebooks provide more insights into the thought process and workflow. \n",
    "\n",
    "## 1. Data Loading & Preprocessing\n",
    "\n",
    "### Data Loading\n",
    "- import libraries\n",
    "- read data from csv file\n",
    "\n",
    "### Data Cleaning & Preparation\n",
    "- choose only useful columns\n",
    "- check and cast data types\n",
    "- check and remove duplicate \n",
    "- discretinization and binning\n",
    "- handling missing data\n",
    "\n",
    "## 2. Eploratory Data Analysis\n",
    "The goal of this exploratory data analysis is to derive insights into which metrics contribute to high points totals. The FPL API provides the same statistics that are available on the transfer page. I have added extra attributes to aid in my analysis during the preprocessing stage.\n",
    "\n",
    "What are we interested in?\n",
    "- High performing teams \n",
    "- High performing positions\n",
    "- High performing players\n",
    "- Undervalued players\n",
    "\n",
    "Both attacking and defensive attributes will be taken into account when looking at the above constraints.\n",
    "\n",
    "High performance will be measured mainly in points per game, total points, value over a season, goals scored, assists, clean sheets, saves, bonus points and G+A (goals and assists combined). Different stats matter depending on the players position and this will be taken into account.\n",
    "\n",
    "Ranking the best attacking teams by goals + assists and the best defensive teams by cleansheets:\n",
    "\n",
    "![](./images/team-bar.PNG)\n",
    "\n",
    "The bar charts provide some useful insights on which teams performed well over the 2021/2022. A high performing team is most likely to include high performing players by virtue of goal contributions and defensive contributions which are the cornerstone for picking players. These are the teams where will choose our base squad from which will have our long-term and premium players.\n",
    "\n",
    "- **Attack**: Chelsea, Liverpool, Man City, Spurs, and West Ham were the only clubs to provide more than 100 combined goals and assists.\n",
    "- **Defence**: Man City, Liverpool, Spurs, Chelsea and Arsenal were the only clubs to provide more than 125 total cleansheets.\n",
    "\n",
    "Season value vs total points:  \n",
    "![](./images/team-scatter.PNG)\n",
    "\n",
    "The uppermost right quandrant in each scatter plot contains the best value & high-performing teams in each statistical category. These are the teams where we would like to choose our base squad from, which will have our long-term and premium players. We have already identified Liverpool, Chelsea, Man City, Spurs, Arsenal and West Ham as teams that fit this criteria which is why they will be ignored in this section. \n",
    "\n",
    "The uppermost left quadrant is the quadrant of interest as this is where the differentials and undervalued players are most likely to come from. These would most likely be teams that are not in the Top 6.\n",
    "\n",
    "- **Upper left/Undervalued Teams**: West Ham, Aston Villa, Crystal Palace, Brentford, and Wolves would have provided good differentials last season.\n",
    "\n",
    "\n",
    "Distribution of points by position:  \n",
    "![](./images/position-dist.PNG)\n",
    "\n",
    "The key takeways from this plot is the heights of the bars. The more times a position's total points is accounted for within a certain range of values, the greater the height of bar.\n",
    "\n",
    "- The positions with the majority of high performing players were in the Midfield and Defense.\n",
    "- Midfielder and Defenders also dominate season points totals greater than 150. Investing heavily in these positions would have yielded great returns over the season. These positions would have been great for long-term investments.\n",
    "- There were only a few high performing Forwards and Goalkeepers to choose from last season. These positions would have been great for short-term investments based on form or fixtures.\n",
    "- The outliers in terms of season points totals (> 250 pts) were  Midfielders, which again shows the great points potential that the midfield had last season.\n",
    "\n",
    "Choosing metrics to evaluate high performing players based on correlation matrix:\n",
    "![](./images/corr.PNG)\n",
    "\n",
    "Here we are interested in the attributes that have dark shades of red or blue in the **total points** row as these have moderate to strong positive/negative correlation. We will only choose the top 4 attributes to plot against the total points attributes.\n",
    "\n",
    "- Points Per Game\n",
    "- Influence\n",
    "- Bonus\n",
    "- ICT Index\n",
    "\n",
    "This plot allows us to find undervalued players at a glance:\n",
    "![](./images/player-scatter-2.PNG)\n",
    "\n",
    "## Conclusion:\n",
    "\n",
    "- We identified Liverpool, Chelsea, Man City, Spurs, Arsenal and West Ham as the best performing teams \n",
    "- Aston Villa, Crystal Palace, Brentford, and Wolves were identified as the teams with the best differentials last season.\n",
    "- High investments in the defense and midfield would have yielded the best returns over the course of last season.\n",
    "- Liverpool had the most high performing players in three out of four generated squads.\n",
    "- Salah and Son were by far the best performing players last season across our four metrics.\n",
    "- **Cash, Gallagher, Toney, Coady, Sa and Ward-Prowse were some of the best undervalued picks of the season.**\n",
    "\n",
    "### To view the code and for more visualizations please check out the notebooks!\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aa4f5107",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
